### ISSUE TITLE
Send Push notifications to one user

### ISSUE THREAD

**Issue by foRsxs** [developerdynamo/laravel-push-notification#1]
Hi, thanks for your job! i have one question, how to send Push notification to one user? Is it possible?
If i want to send message personal only one user, how i can to do this?

**Comment by ilvalerione** [comment]
By your eloquent model you can apply your own criteria to select devices to send a push notification, so you can select only one device or all devices in your DB:

`
//Retrieve devices list with your own criteria
$tokens = YourPushTokenTable::where('user_id', 1)->get();

//send directly
NotificationBridge::send($payload, $tokens);
`

**Comment by foRsxs** [comment]
Thanks for your answer! I cant find info how to get token devices and save to YourPushTokenTable,

**Comment by ilvalerione** [comment]
This package is for Laravel Framework, do you know Eloquent ORM?

**Comment by foRsxs** [comment]
I know Eloquent ORM and i know how to save this model and how to get data from DB, but i dont understand where is to get token devices from client.

**Comment by ilvalerione** [comment]
Your table to store devices informations needs to have a column user_id (for example) to inplement relation with your users table. So you can run 

YourPushTokenTable::where('user_id', 1)->get();

To retrieve device information for specific user with ID =1.

This is kust an example, but it's depend on your PushTokenTable is structured.

**Comment by foRsxs** [comment]
PushTokenTable in DB my table is empty, i dont understand how to fill table )) I know how to get data from Eloquent ORM :)

**Comment by ilvalerione** [comment]
You get devices informations from devices with your app installed.

When user open your app on the smartphone your app needs to require a registration id from GCM (for android app) or APS (for ios app) and forward this informations to your backend.

You can store this information (platform and device_token) by your PushTokenTable for your specific user.
